package com.example.sbassignment.screens.camera

import android.Manifest
import android.content.pm.PackageManager
import android.util.Log
import android.widget.Toast
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.camera.core.CameraSelector
import androidx.camera.core.ExperimentalGetImage
import androidx.camera.core.ImageAnalysis
import androidx.camera.core.ImageCapture
import androidx.camera.core.ImageCaptureException
import androidx.camera.core.ImageProxy
import androidx.camera.mlkit.vision.MlKitAnalyzer
import androidx.camera.view.CameraController
import androidx.camera.view.LifecycleCameraController
import androidx.camera.view.PreviewView
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.navigationBarsPadding
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.statusBarsPadding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.KeyboardArrowLeft
import androidx.compose.material3.Button
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.platform.LocalLifecycleOwner
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.core.content.ContextCompat
import com.example.sbassignment.R
import com.example.sbassignment.face.FaceCropper
import com.example.sbassignment.face.FaceImageUtils
import com.example.sbassignment.face.FaceNetModel
import com.google.mlkit.vision.common.InputImage
import com.google.mlkit.vision.face.FaceDetection
import com.google.mlkit.vision.face.FaceDetectorOptions
import java.util.concurrent.Executors

@OptIn(ExperimentalGetImage::class)
@Composable
fun FaceCameraScreen(staffId: String, onBack: () -> Unit) {
    val context = LocalContext.current

    LaunchedEffect(Unit) {
        Toast.makeText(context, "FaceCameraScreen is running", Toast.LENGTH_LONG).show()
    }

    val lifecycleOwner = LocalLifecycleOwner.current
    val density = LocalDensity.current

    val detectorOptions = remember { FaceDetectorOptions.Builder()
        .setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE)
        .setContourMode(FaceDetectorOptions.CONTOUR_MODE_ALL)
        .setMinFaceSize(0.25f)
        .build()
    }

    // Face variables
    var faceDetected by remember { mutableStateOf(false) }
    val faceNetModel = remember { FaceNetModel(context) }
    val faceDetector = remember { FaceDetection.getClient(detectorOptions) }

    // Controller
    val cameraController = remember { LifecycleCameraController(context) }
    cameraController.cameraSelector = CameraSelector.DEFAULT_FRONT_CAMERA
    var isProcessing by remember { mutableStateOf(false) }
    var embeddingGenerated by remember { mutableStateOf(false) }


    DisposableEffect(Unit) {
        onDispose {
            faceDetector.close()
            faceNetModel.close()
            cameraController.unbind()
        }
    }

    var hasCameraPermission by remember {
        mutableStateOf(
            ContextCompat.checkSelfPermission(
                context,
                Manifest.permission.CAMERA
            ) == PackageManager.PERMISSION_GRANTED
        )
    }

    val permissionLauncher = rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()) { granted ->
            hasCameraPermission = granted
        }

    LaunchedEffect(Unit) {
        if (!hasCameraPermission) {
            permissionLauncher.launch(Manifest.permission.CAMERA)
        }
    }

    if(!hasCameraPermission) {
        Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
            Text("Camera permission is required")
        }
        return
    }

    val cameraExecutor = remember { Executors.newSingleThreadExecutor() }

    DisposableEffect(Unit) {
        onDispose {
            cameraExecutor.shutdown()
        }
    }

    Box(modifier = Modifier.fillMaxSize()) {
        // CAMERA PREVIEW
        AndroidView(
            modifier = Modifier.fillMaxSize(),
            factory = { ctx ->

                val previewView = PreviewView(ctx).apply {
                    scaleType = PreviewView.ScaleType.FILL_CENTER
                }

                cameraController.setEnabledUseCases(
                    CameraController.IMAGE_CAPTURE or CameraController.IMAGE_ANALYSIS
                )

                cameraController.setImageAnalysisBackpressureStrategy(
                    ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST
                )

                val mainExecutor = ContextCompat.getMainExecutor(ctx)
                val mlKitAnalyzer = MlKitAnalyzer(
                    listOf(faceDetector),
                    CameraController.COORDINATE_SYSTEM_VIEW_REFERENCED,
                    mainExecutor
                ) { result ->

                    val faces = result?.getValue(faceDetector)
                    val face = faces?.firstOrNull()
                    if (face == null) {
                        faceDetected = false
                        return@MlKitAnalyzer
                    }

                    // Face orientation
                    val frontal = kotlin.math.abs(face.headEulerAngleY) <= 20f &&
                                kotlin.math.abs(face.headEulerAngleZ) <= 15f
                    if (!frontal) {
                        faceDetected = false
                        return@MlKitAnalyzer
                    }

                    // 3. FRAME COORDINATES
                    val frameSizePx = with(density) { 280.dp.toPx() }
                    val previewWidth = previewView.width.toFloat()
                    val previewHeight = previewView.height.toFloat()

                    if (previewWidth <= 0f ||previewHeight <= 0f) {
                        faceDetected = false
                        return@MlKitAnalyzer
                    }

                    val frameLeft = (previewWidth - frameSizePx) / 2f
                    val frameTop = (previewHeight - frameSizePx) / 2f
                    val frameRight = frameLeft + frameSizePx
                    val frameBottom = frameTop + frameSizePx

                    // 4. ML KIT BOUNDING BOX IS NOW ALREADY IN PREVIEWVIEW COORDINATES
                    val faceRect = face.boundingBox
                    val insideFrame =
                        faceRect.left >= frameLeft &&
                        faceRect.top >= frameTop &&
                        faceRect.right <= frameRight &&
                        faceRect.bottom <= frameBottom

                    faceDetected = insideFrame
                }

                cameraController.setImageAnalysisAnalyzer(cameraExecutor, mlKitAnalyzer)

                previewView.controller = cameraController

                cameraController.bindToLifecycle(lifecycleOwner)

                previewView
            }
        )

        // TOP BAR
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .statusBarsPadding()
                .padding(horizontal = 16.dp,vertical = 12.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            IconButton(onClick = onBack) {
                Icon(
                    imageVector = Icons.AutoMirrored.Filled.KeyboardArrowLeft,
                    contentDescription = "Back"
                )
            }
            Text(text = "Face Verification", style = MaterialTheme.typography.titleLarge)
        }

        // INSTRUCTION
        Text(
            text = when {
                isProcessing -> "Processing face..."
                embeddingGenerated -> "Face embedding generated"
                faceDetected -> "Face detected"
                else -> "Position your face inside the frame"
            },
            modifier = Modifier
                .align(Alignment.TopCenter)
                .statusBarsPadding()
                .padding(top = 72.dp),
            style = MaterialTheme.typography.bodyLarge
        )

        // FACE FRAME
        Box(modifier = Modifier
                .size(280.dp)
                .align(Alignment.Center)
                .border(
                    width = 3.dp,
                    color = if (faceDetected) Color.Green else Color.White,
                    shape = RoundedCornerShape(24.dp)
                )
        )

        // CAPTURE BUTTON
        Button(
            enabled = !isProcessing,
            onClick = {
                if (!faceDetected) {
                    Toast.makeText(context, "Position your face inside the frame first", Toast.LENGTH_SHORT).show()
                    return@Button
                }
                if (isProcessing) return@Button

                isProcessing = true
                embeddingGenerated = false

                cameraController.takePicture(
                    cameraExecutor,
                    object : ImageCapture.OnImageCapturedCallback() {
                        override fun onCaptureSuccess(image: ImageProxy) {
                            try {
                                Log.d("FACE_RECOGNITION", "========== IMAGE CAPTURED ==========")
                                val bitmap = FaceImageUtils.imageProxyToBitmap(image)
                                if (bitmap == null) {
                                    ContextCompat
                                        .getMainExecutor(context)
                                        .execute {
                                            isProcessing = false
                                            Toast.makeText(context, "Could not process captured image", Toast.LENGTH_SHORT).show()
                                        }
                                    return
                                }
                                Log.d("FACE_RECOGNITION", "Bitmap: ${bitmap.width} x ${bitmap.height}")

                                // Run ML Kit on the SAME bitmap
                                // that we will crop.
                                val inputImage = InputImage.fromBitmap(bitmap, 0)

                                faceDetector
                                    .process(inputImage)
                                    .addOnSuccessListener(
                                        cameraExecutor
                                    ) { faces ->
                                        val face = faces.firstOrNull()
                                        if (face == null) {
                                            ContextCompat
                                                .getMainExecutor(context)
                                                .execute {
                                                    isProcessing = false
                                                    Toast.makeText(context, "No face found in captured image", Toast.LENGTH_SHORT).show()
                                                }
                                            bitmap.recycle()
                                            return@addOnSuccessListener
                                        }

                                        Log.d("FACE_RECOGNITION", "Captured face: ${face.boundingBox}")

                                        val croppedFace = FaceCropper.cropFace(bitmap, face.boundingBox)
                                        if (croppedFace == null) {
                                            ContextCompat
                                                .getMainExecutor(context)
                                                .execute {
                                                    isProcessing = false
                                                    Toast.makeText(context, "Could not crop face", Toast.LENGTH_SHORT).show()
                                                }
                                            bitmap.recycle()
                                            return@addOnSuccessListener
                                        }

                                        Log.d("FACE_RECOGNITION", "Face crop: ${croppedFace.width} x ${croppedFace.height}")
                                        Log.e("FACE_RECOGNITION", "Sending face crop to FaceNet: ${croppedFace.width} x ${croppedFace.height}")

                                        val embedding = faceNetModel.getEmbedding(croppedFace)

                                        Log.e("FACE_RECOGNITION", "========== EMBEDDING GENERATED ==========")
                                        Log.e("FACE_RECOGNITION", "Embedding size = ${embedding.size}")

                                        var norm = 0f
                                        for (value in embedding) {
                                            norm += value * value
                                        }
                                        norm = kotlin.math.sqrt(norm)

                                        Log.e("FACE_RECOGNITION", "Embedding L2 norm = $norm")

                                        croppedFace.recycle()
                                        bitmap.recycle()

                                        ContextCompat
                                            .getMainExecutor(context)
                                            .execute {
                                                isProcessing = false
                                                embeddingGenerated = true
                                                Toast.makeText(context, "Face embedding generated successfully", Toast.LENGTH_SHORT).show()
                                            }
                                    }
                                    .addOnFailureListener(cameraExecutor) { exception ->
                                        Log.e("FACE_RECOGNITION", "ML Kit capture detection failed", exception)

                                        bitmap.recycle()

                                        ContextCompat
                                            .getMainExecutor(context)
                                            .execute {
                                                isProcessing = false
                                                Toast.makeText(context, "Face processing failed", Toast.LENGTH_SHORT).show()
                                            }
                                    }
                            } catch (e: Exception) {

                                Log.e("FACE_RECOGNITION", "Face recognition pipeline failed", e)

                                ContextCompat
                                    .getMainExecutor(context)
                                    .execute {
                                        isProcessing = false
                                        Toast.makeText(context, "Face processing error: ${e.javaClass.simpleName}", Toast.LENGTH_LONG).show()
                                    }

                            } finally {
                                // ImageCapture requires the application
                                // to close the returned ImageProxy.
                                image.close()
                            }
                        }
                        override fun onError(exception: ImageCaptureException) {
                            Log.e("FACE_RECOGNITION", "Image capture failed", exception)

                            ContextCompat
                                .getMainExecutor(context)
                                .execute {
                                    isProcessing = false
                                    Toast.makeText(context, "Camera capture failed", Toast.LENGTH_SHORT).show()
                                }
                        }
                    }
                )

            },
            shape = RoundedCornerShape(16.dp),
            modifier = Modifier
                .align(Alignment.BottomCenter)
                .navigationBarsPadding()
                .padding(bottom = 32.dp)
        ) {

            Icon(
                painter = painterResource(
                    R.drawable.outline_camera_alt_24
                ),
                contentDescription = "Capture"
            )
        }
    }
}